spring.application.name=spring1proj

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.rmgcebyfrgubspwebwoe
spring.datasource.password=C5hyK0APxL5O3B4J
spring.datasource.driver-class-name=org.postgresql.Driver